
format = """
[░▒▓](#{color1.strip})\
[  ](bg:#{color1.strip} fg:#{foreground.strip})\
[](bg:#{color2.strip} fg:#{color1.strip})\
$directory\
[](fg:#{color2.strip} bg:#{color3.strip})\
$git_branch\
$git_status\
[](fg:#{color3.strip} bg:#{color4.strip})\
$nodejs\
$rust\
$golang\
$php\
[](fg:#{color4.strip} bg:#{color5.strip})\
$time\
[ ](fg:#{color5.strip})\
\n$character"""

[directory]
style = "fg:#{foreground.strip} bg:#{color2.strip}"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#{color3.strip}"
format = '[[ $symbol $branch ](fg:#{foreground.strip} bg:#{color3.strip})]($style)'

[git_status]
style = "bg:#{color3.strip}"
format = '[[($all_status$ahead_behind )](fg:#{foreground.strip} bg:#{color3.strip})]($style)'

[nodejs]
symbol = ""
style = "bg:#{color4.strip}"
format = '[[ $symbol ($version) ](fg:#{foreground.strip} bg:#{color4.strip})]($style)'

[rust]
symbol = ""
style = "bg:#{color4.strip}"
format = '[[ $symbol ($version) ](fg:#{foreground.strip} bg:#{color4.strip})]($style)'

[golang]
symbol = ""
style = "bg:#{color4.strip}"
format = '[[ $symbol ($version) ](fg:#{foreground.strip} bg:#{color4.strip})]($style)'

[php]
symbol = ""
style = "bg:#{color4.strip}"
format = '[[ $symbol ($version) ](fg:#{foreground.strip} bg:#{color4.strip})]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#{color5.strip}"
format = '[[  $time ](fg:#{foreground.strip} bg:#{color5.strip})]($style)'
